// use alloy_primitives::{Address, Bytes, B256, U256};
use ethers::types::Log;
use ethers::types::{Bytes, H160, H256, U256};
use serde::{Deserialize, Serialize};

pub type Address = H160;
// pub type B256 = H256;

#[derive(Debug, Deserialize, Default)]
#[cfg_attr(feature = "client", derive(Serialize))]
pub struct Bundle {
    pub version: String,
    pub inclusion: BundleInclusion,
    pub body: Vec<BundleBody>,
    pub validity: BundleValidity,
    pub privacy: Option<BundlePrivacy>,
    pub metadata: Option<BundleMetadata>,
}

#[derive(Debug, Deserialize, Default)]
#[cfg_attr(feature = "client", derive(Serialize))]
pub struct BundleInclusion {
    pub block: u64,
    #[serde(alias = "maxBlock")]
    pub max_block: Option<u64>,
}

#[derive(Debug, Deserialize)]
#[cfg_attr(feature = "client", derive(Serialize))]
pub struct BundleBody {
    pub hash: Option<H256>,
    pub tx: Option<Bytes>,
    pub bundle: Option<Bundle>,
    #[serde(alias = "canRevert")]
    pub can_revert: Option<bool>,
}

#[derive(Debug, Deserialize, Default)]
#[cfg_attr(feature = "client", derive(Serialize))]
pub struct BundleValidity {
    /// Specifies the minimum percent of a given bundle's earnings to redistribute for it to be included in a builder's block.
    pub refund: Vec<RefundConstraint>,
    /// Specifies what addresses should receive what percent of the overall refund for this bundle, if it is enveloped by another bundle (eg. a searcher backrun). The sum of percents in this array should equal 100.
    #[serde(alias = "refundConfig")]
    pub refund_config: Vec<RefundConfig>,
}

#[derive(Debug, Deserialize)]
#[cfg_attr(feature = "client", derive(Serialize))]
pub struct RefundConstraint {
    /// Index of the entry in body to which the refund percentage applies.
    #[serde(alias = "bodyIdx")]
    pub body_idx: u64,
    /// Minimum refund percentage required for this bundle to be eligible for use by another searcher, paid by said searcher from the profit generated by including this bundle in theirs.
    pub percent: u64,
}

#[derive(Debug, Deserialize)]
#[cfg_attr(feature = "client", derive(Serialize))]
pub struct RefundConfig {
    /// Address which receives the portion of the refund.
    pub address: Address,
    /// Percentage of refund to pay to the address.
    pub percent: u64,
}

/// Preferences on what data should be shared about the bundle and its transactions.
#[derive(Debug, Deserialize)]
#[cfg_attr(feature = "client", derive(Serialize))]
pub struct BundlePrivacy {
    /// Each item additively specifies which data about all transactions in the bundle to share. If no hints are specified, no data is shared. Transactions from other users that do not specify the same hints will not share additional information.
    pub hints: Vec<Hint>,
    /// Builders that have permission to receive this bundle and include it in a block.
    pub builders: Vec<String>,
}

#[derive(Debug, Deserialize)]
#[cfg_attr(feature = "client", derive(Serialize))]
#[serde(rename_all = "camelCase")]
pub struct BundleMetadata {
    pub bundle_hash: Bytes,
    pub body_hashes: Vec<Bytes>,
    pub signer: Address,
    pub origin_id: String,
    pub received_at: u64,
}

#[derive(Debug, Deserialize, Clone, strum::Display)]
#[cfg_attr(feature = "client", derive(Serialize))]
#[strum(serialize_all = "snake_case")]
pub enum Hint {
    Calldata,
    ContractAddress,
    Logs,
    FunctionSelector,
    Hash,
    TxHash,
}

pub type BundleHash = H256;

#[derive(Debug, Deserialize, Serialize, Clone, Default)]
#[serde(rename_all = "camelCase")]
pub struct SendBundleResponse {
    pub bundle_hash: H256,
}

#[derive(Debug, Deserialize, Serialize, Clone, Default)]
#[serde(rename_all = "camelCase")]
pub struct SimulateBundleResponse {
    pub success: bool,
    pub error: String,
    pub state_block: u64,
    pub mev_gas_price: U256,
    pub profit: U256,
    pub refundable_value: U256,
    pub gas_used: u64,
    pub body_logs: Vec<SimulateMevBodyLog>,
}

#[derive(Debug, Deserialize, Serialize, Clone)]
pub struct SimulateMevBodyLog {
    pub tx_logs: Vec<Log>,
    pub bundle_logs: Vec<SimulateMevBodyLog>,
}

#[derive(Debug, Deserialize, Serialize, Clone, Default)]
pub struct CancelBundleResponse {}
